### ISSUE TITLE
Upgrading to Kotest 5.7.1 leads to errors in NonEmptyList.forOne assertions

### ISSUE THREAD

**Issue by Zordid** [kotest/kotest-extensions-arrow#247]
When coming from Kotest 5.6.2 with kotest-extensions-arrow 1.3.3 and upgrading to Kotest 5.7.1, using the matcher 
`io.kotest.assertions.arrow.core.forOne` leads to this exception

    java.lang.NoSuchMethodError: 'void io.kotest.inspectors.ElementFail.<init>(java.lang.Object, java.lang.Throwable)'
	at io.kotest.assertions.arrow.core.NelnspectorsKt.forOne(Nelnspectors.kt:104)

Workaround is to explicitly cast the `Nel` to a `Collection` and use the Kotest matcher `io.kotest.inspectors.forOne` instead!

Could it be that this extension needs to be updated to work with Kotest 5.7?

**Comment by Zordid** [comment]
Hm, not a very active project here?

**Comment by myuwono** [comment]
I'll raise a PR really soon @Zordid sorry been caught in various work commitments

**Comment by Zordid** [comment]
Thanks @myuwono !
