### PR TITLE
upgrade kotest

### LINKED ISSUE #247: Upgrading to Kotest 5.7.1 leads to errors in NonEmptyList.forOne assertions
When coming from Kotest 5.6.2 with kotest-extensions-arrow 1.3.3 and upgrading to Kotest 5.7.1, using the matcher 
`io.kotest.assertions.arrow.core.forOne` leads to this exception

    java.lang.NoSuchMethodError: 'void io.kotest.inspectors.ElementFail.<init>(java.lang.Object, java.lang.Throwable)'
	at io.kotest.assertions.arrow.core.NelnspectorsKt.forOne(Nelnspectors.kt:104)

Workaround is to explicitly cast the `Nel` to a `Collection` and use the Kotest matcher `io.kotest.inspectors.forOne` instead!

Could it be that this extension needs to be updated to work with Kotest 5.7?

### PR DESCRIPTION
**Pull request by myuwono**
# In this PR
- upgrade kotest to 5.7.2
- mark nonemptylist inspectors as deprecated

fixes #247

### CODE REVIEW

**Review by nomisRev — APPROVED** [review]
Looks great @myuwono ! 🙌

**Review by i-walker — APPROVED** [review]
Thanks @myuwono ! 🙌🏾
